project_id = "ohsxncrxdqbsuxwybrjp"

[functions.send-contact-to-discord]
verify_jwt = false

[functions.add-user-to-discord-server]
verify_jwt = true

[functions.translate-review]
verify_jwt = false

[functions.send-order-to-discord]
verify_jwt = false

[functions.send-deletion-to-discord]
verify_jwt = false
